// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/25/2026, 4:41:20 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/huangyuping/Desktop/rupiong/blog/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huangyuping/Desktop/rupiong/blog/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huangyuping/Desktop/rupiong/blog/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huangyuping/Desktop/rupiong/blog/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huangyuping/Desktop/rupiong/blog/src/plugins/**/*.{js,ts,mjs}","/Users/huangyuping/Desktop/rupiong/blog/src/composables/**/*.{js,ts,mjs}","/Users/huangyuping/Desktop/rupiong/blog/src/utils/**/*.{js,ts,mjs}","/Users/huangyuping/Desktop/rupiong/blog/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huangyuping/Desktop/rupiong/blog/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/huangyuping/Desktop/rupiong/blog/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/huangyuping/Desktop/rupiong/blog/src/app.config.{js,ts,mjs}"]}},
{"theme":{"extend":{"colors":{"primary":"#00DC82 ","secondary":"#69B9F1","success":"#1EB11C","error":"#E71609","warning":"#FFFF00"}}}}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;