// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/26/2026, 6:26:03 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/huangyuping/Desktop/个人项目/blog/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huangyuping/Desktop/个人项目/blog/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huangyuping/Desktop/个人项目/blog/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huangyuping/Desktop/个人项目/blog/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huangyuping/Desktop/个人项目/blog/src/plugins/**/*.{js,ts,mjs}","/Users/huangyuping/Desktop/个人项目/blog/src/composables/**/*.{js,ts,mjs}","/Users/huangyuping/Desktop/个人项目/blog/src/utils/**/*.{js,ts,mjs}","/Users/huangyuping/Desktop/个人项目/blog/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/huangyuping/Desktop/个人项目/blog/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/huangyuping/Desktop/个人项目/blog/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/huangyuping/Desktop/个人项目/blog/src/app.config.{js,ts,mjs}"]}},
{"darkMode":"class","theme":{"extend":{"colors":{"primary":"#00DC82 ","secondary":"#69B9F1","success":"#1EB11C","error":"#E71609","warning":"#FFFF00"}}},"sizes":() => ({"16":"16px","20":"20px","24":"24px","28":"28px","32":"32px","36":"36px","40":"40px","44":"44px","48":"48px","52":"52px","56":"56px","60":"60px","64":"64px","68":"68px","72":"72px","76":"76px","80":"80px","84":"84px","88":"88px","92":"92px","96":"96px","100":"100px"})}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;